class EthernetRunner {

    public static void main(String[] args) {

        Ethernet e1 = new Ethernet();
        Ethernet e2 = new Ethernet();
        Ethernet e3 = new Ethernet();
        Ethernet e4 = new Ethernet();
        Ethernet e5 = new Ethernet();
        Ethernet e6 = new Ethernet();
        Ethernet e7 = new Ethernet();
        Ethernet e8 = new Ethernet();
        Ethernet e9 = new Ethernet();
        Ethernet e10 = new Ethernet();

        e1.price = 500;
        e1.model = "Cat5";
        e1.category = "Cat5";
        e1.dataRate = 100;
        e1.connectorType = "RJ45";
        e1.isAvailable = true;
        e1.warranty = 1;
        e1.shielding = "UTP";
        e1.weight = 0.2;
        e1.compatibility = "Router";

        e2.price = 700;
        e2.model = "Cat5e";
        e2.category = "Cat5e";
        e2.dataRate = 1000;
        e2.connectorType = "RJ45";
        e2.isAvailable = true;
        e2.warranty = 2;
        e2.shielding = "UTP";
        e2.weight = 0.25;
        e2.compatibility = "Switch";

        e3.price = 900;
        e3.model = "Cat6";
        e3.category = "Cat6";
        e3.dataRate = 1000;
        e3.connectorType = "RJ45";
        e3.isAvailable = true;
        e3.warranty = 2;
        e3.shielding = "STP";
        e3.weight = 0.3;
        e3.compatibility = "Router";

        e4.price = 1200;
        e4.model = "Cat6a";
        e4.category = "Cat6a";
        e4.dataRate = 10000;
        e4.connectorType = "RJ45";
        e4.isAvailable = true;
        e4.warranty = 3;
        e4.shielding = "STP";
        e4.weight = 0.35;
        e4.compatibility = "Server";

        e5.price = 1500;
        e5.model = "Cat7";
        e5.category = "Cat7";
        e5.dataRate = 10000;
        e5.connectorType = "RJ45";
        e5.isAvailable = true;
        e5.warranty = 3;
        e5.shielding = "SSTP";
        e5.weight = 0.4;
        e5.compatibility = "Server";

        e6.price = 1800;
        e6.model = "Cat8";
        e6.category = "Cat8";
        e6.dataRate = 40000;
        e6.connectorType = "RJ45";
        e6.isAvailable = true;
        e6.warranty = 4;
        e6.shielding = "SSTP";
        e6.weight = 0.45;
        e6.compatibility = "Data Center";

        e7.price = 600;
        e7.model = "Cat5 Basic";
        e7.category = "Cat5";
        e7.dataRate = 100;
        e7.connectorType = "RJ45";
        e7.isAvailable = false;
        e7.warranty = 1;
        e7.shielding = "UTP";
        e7.weight = 0.22;
        e7.compatibility = "Router";

        e8.price = 800;
        e8.model = "Cat6 Lite";
        e8.category = "Cat6";
        e8.dataRate = 1000;
        e8.connectorType = "RJ45";
        e8.isAvailable = true;
        e8.warranty = 2;
        e8.shielding = "STP";
        e8.weight = 0.28;
        e8.compatibility = "Switch";

        e9.price = 1300;
        e9.model = "Cat7 Pro";
        e9.category = "Cat7";
        e9.dataRate = 10000;
        e9.connectorType = "RJ45";
        e9.isAvailable = true;
        e9.warranty = 3;
        e9.shielding = "SSTP";
        e9.weight = 0.38;
        e9.compatibility = "Server";

        e10.price = 2000;
        e10.model = "Cat8 Ultra";
        e10.category = "Cat8";
        e10.dataRate = 40000;
        e10.connectorType = "RJ45";
        e10.isAvailable = true;
        e10.warranty = 5;
        e10.shielding = "SSTP";
        e10.weight = 0.5;
        e10.compatibility = "Data Center";


        System.out.println("\nEthernet1 Details");
        System.out.println("Brand: " + e1.brand);
        System.out.println("Color: " + e1.color);
        System.out.println("Type: " + e1.type);
        System.out.println("High Speed: " + e1.supportsHighSpeed);
        System.out.println("Length: " + e1.length);
        System.out.println("Price: " + e1.price);
        System.out.println("Model: " + e1.model);
        System.out.println("Category: " + e1.category);
        System.out.println("Data Rate: " + e1.dataRate);
        System.out.println("Connector: " + e1.connectorType);
        System.out.println("Available: " + e1.isAvailable);
        System.out.println("Warranty: " + e1.warranty);
        System.out.println("Shielding: " + e1.shielding);
        System.out.println("Weight: " + e1.weight);
        System.out.println("Compatibility: " + e1.compatibility);

        System.out.println("\nEthernet2 Details");
        System.out.println("Brand: " + e2.brand);
        System.out.println("Color: " + e2.color);
        System.out.println("Type: " + e2.type);
        System.out.println("High Speed: " + e2.supportsHighSpeed);
        System.out.println("Length: " + e2.length);
        System.out.println("Price: " + e2.price);
        System.out.println("Model: " + e2.model);
        System.out.println("Category: " + e2.category);
        System.out.println("Data Rate: " + e2.dataRate);
        System.out.println("Connector: " + e2.connectorType);
        System.out.println("Available: " + e2.isAvailable);
        System.out.println("Warranty: " + e2.warranty);
        System.out.println("Shielding: " + e2.shielding);
        System.out.println("Weight: " + e2.weight);
        System.out.println("Compatibility: " + e2.compatibility);

                System.out.println("\nEthernet3 Details");
        System.out.println("Brand: " + e3.brand);
        System.out.println("Color: " + e3.color);
        System.out.println("Type: " + e3.type);
        System.out.println("High Speed: " + e3.supportsHighSpeed);
        System.out.println("Length: " + e3.length);
        System.out.println("Price: " + e3.price);
        System.out.println("Model: " + e3.model);
        System.out.println("Category: " + e3.category);
        System.out.println("Data Rate: " + e3.dataRate);
        System.out.println("Connector: " + e3.connectorType);
        System.out.println("Available: " + e3.isAvailable);
        System.out.println("Warranty: " + e3.warranty);
        System.out.println("Shielding: " + e3.shielding);
        System.out.println("Weight: " + e3.weight);
        System.out.println("Compatibility: " + e3.compatibility);

        System.out.println("\nEthernet4 Details");
        System.out.println("Brand: " + e4.brand);
        System.out.println("Color: " + e4.color);
        System.out.println("Type: " + e4.type);
        System.out.println("High Speed: " + e4.supportsHighSpeed);
        System.out.println("Length: " + e4.length);
        System.out.println("Price: " + e4.price);
        System.out.println("Model: " + e4.model);
        System.out.println("Category: " + e4.category);
        System.out.println("Data Rate: " + e4.dataRate);
        System.out.println("Connector: " + e4.connectorType);
        System.out.println("Available: " + e4.isAvailable);
        System.out.println("Warranty: " + e4.warranty);
        System.out.println("Shielding: " + e4.shielding);
        System.out.println("Weight: " + e4.weight);
        System.out.println("Compatibility: " + e4.compatibility);

        System.out.println("\nEthernet5 Details");
        System.out.println("Brand: " + e5.brand);
        System.out.println("Color: " + e5.color);
        System.out.println("Type: " + e5.type);
        System.out.println("High Speed: " + e5.supportsHighSpeed);
        System.out.println("Length: " + e5.length);
        System.out.println("Price: " + e5.price);
        System.out.println("Model: " + e5.model);
        System.out.println("Category: " + e5.category);
        System.out.println("Data Rate: " + e5.dataRate);
        System.out.println("Connector: " + e5.connectorType);
        System.out.println("Available: " + e5.isAvailable);
        System.out.println("Warranty: " + e5.warranty);
        System.out.println("Shielding: " + e5.shielding);
        System.out.println("Weight: " + e5.weight);
        System.out.println("Compatibility: " + e5.compatibility);

        System.out.println("\nEthernet6 Details");
        System.out.println("Brand: " + e6.brand);
        System.out.println("Color: " + e6.color);
        System.out.println("Type: " + e6.type);
        System.out.println("High Speed: " + e6.supportsHighSpeed);
        System.out.println("Length: " + e6.length);
        System.out.println("Price: " + e6.price);
        System.out.println("Model: " + e6.model);
        System.out.println("Category: " + e6.category);
        System.out.println("Data Rate: " + e6.dataRate);
        System.out.println("Connector: " + e6.connectorType);
        System.out.println("Available: " + e6.isAvailable);
        System.out.println("Warranty: " + e6.warranty);
        System.out.println("Shielding: " + e6.shielding);
        System.out.println("Weight: " + e6.weight);
        System.out.println("Compatibility: " + e6.compatibility);

        System.out.println("\nEthernet7 Details");
        System.out.println("Brand: " + e7.brand);
        System.out.println("Color: " + e7.color);
        System.out.println("Type: " + e7.type);
        System.out.println("High Speed: " + e7.supportsHighSpeed);
        System.out.println("Length: " + e7.length);
        System.out.println("Price: " + e7.price);
        System.out.println("Model: " + e7.model);
        System.out.println("Category: " + e7.category);
        System.out.println("Data Rate: " + e7.dataRate);
        System.out.println("Connector: " + e7.connectorType);
        System.out.println("Available: " + e7.isAvailable);
        System.out.println("Warranty: " + e7.warranty);
        System.out.println("Shielding: " + e7.shielding);
        System.out.println("Weight: " + e7.weight);
        System.out.println("Compatibility: " + e7.compatibility);

        System.out.println("\nEthernet8 Details");
        System.out.println("Brand: " + e8.brand);
        System.out.println("Color: " + e8.color);
        System.out.println("Type: " + e8.type);
        System.out.println("High Speed: " + e8.supportsHighSpeed);
        System.out.println("Length: " + e8.length);
        System.out.println("Price: " + e8.price);
        System.out.println("Model: " + e8.model);
        System.out.println("Category: " + e8.category);
        System.out.println("Data Rate: " + e8.dataRate);
        System.out.println("Connector: " + e8.connectorType);
        System.out.println("Available: " + e8.isAvailable);
        System.out.println("Warranty: " + e8.warranty);
        System.out.println("Shielding: " + e8.shielding);
        System.out.println("Weight: " + e8.weight);
        System.out.println("Compatibility: " + e8.compatibility);

        System.out.println("\nEthernet9 Details");
        System.out.println("Brand: " + e9.brand);
        System.out.println("Color: " + e9.color);
        System.out.println("Type: " + e9.type);
        System.out.println("High Speed: " + e9.supportsHighSpeed);
        System.out.println("Length: " + e9.length);
        System.out.println("Price: " + e9.price);
        System.out.println("Model: " + e9.model);
        System.out.println("Category: " + e9.category);
        System.out.println("Data Rate: " + e9.dataRate);
        System.out.println("Connector: " + e9.connectorType);
        System.out.println("Available: " + e9.isAvailable);
        System.out.println("Warranty: " + e9.warranty);
        System.out.println("Shielding: " + e9.shielding);
        System.out.println("Weight: " + e9.weight);
        System.out.println("Compatibility: " + e9.compatibility);

        System.out.println("\nEthernet10 Details");
        System.out.println("Brand: " + e10.brand);
        System.out.println("Color: " + e10.color);
        System.out.println("Type: " + e10.type);
        System.out.println("High Speed: " + e10.supportsHighSpeed);
        System.out.println("Length: " + e10.length);
        System.out.println("Price: " + e10.price);
        System.out.println("Model: " + e10.model);
        System.out.println("Category: " + e10.category);
        System.out.println("Data Rate: " + e10.dataRate);
        System.out.println("Connector: " + e10.connectorType);
        System.out.println("Available: " + e10.isAvailable);
        System.out.println("Warranty: " + e10.warranty);
        System.out.println("Shielding: " + e10.shielding);
        System.out.println("Weight: " + e10.weight);
        System.out.println("Compatibility: " + e10.compatibility);
    }
}