class MouseRunner {

    public static void main(String[] args) {

        Mouse mouse1 = new Mouse();
        Mouse mouse2 = new Mouse();
        Mouse mouse3 = new Mouse();
        Mouse mouse4 = new Mouse();
        Mouse mouse5 = new Mouse();
        Mouse mouse6 = new Mouse();
        Mouse mouse7 = new Mouse();
        Mouse mouse8 = new Mouse();
        Mouse mouse9 = new Mouse();
        Mouse mouse10 = new Mouse();

		mouse1.price = 500;
		mouse1.type = "Gaming";
		mouse1.isWireless = true;
		mouse1.weight = 150;
		mouse1.sensorType = "Optical";
		mouse1.warranty = 1;
		mouse1.compatibility = "Windows";
		mouse1.isAvailable = true;
		mouse1.shape = "Ergonomic";
		mouse1.cableLength = 1.5;
		
		mouse2.price = 600;
		mouse2.type = "Office";
		mouse2.isWireless = false;
		mouse2.weight = 140;
		mouse2.sensorType = "Laser";
		mouse2.warranty = 2;
		mouse2.compatibility = "Mac";
		mouse2.isAvailable = true;
		mouse2.shape = "Compact";
		mouse2.cableLength = 1.2;

		mouse3.price = 700;
		mouse3.type = "Gaming";
		mouse3.isWireless = true;
		mouse3.weight = 160;
		mouse3.sensorType = "Optical";
		mouse3.warranty = 1;
		mouse3.compatibility = "Windows";
		mouse3.isAvailable = false;
		mouse3.shape = "Ergonomic";
		mouse3.cableLength = 1.8;

		mouse4.price = 800;
		mouse4.type = "Office";
		mouse4.isWireless = false;
		mouse4.weight = 130;
		mouse4.sensorType = "Laser";
		mouse4.warranty = 2;
		mouse4.compatibility = "Linux";
		mouse4.isAvailable = true;
		mouse4.shape = "Compact";
		mouse4.cableLength = 1.0;

		mouse5.price = 900;
		mouse5.type = "Gaming";
		mouse5.isWireless = true;
		mouse5.weight = 155;
		mouse5.sensorType = "Optical";
		mouse5.warranty = 1;
		mouse5.compatibility = "Windows";
		mouse5.isAvailable = true;
		mouse5.shape = "Ergonomic";
		mouse5.cableLength = 1.6;

		mouse6.price = 1000;
		mouse6.type = "Office";
		mouse6.isWireless = false;
		mouse6.weight = 135;
		mouse6.sensorType = "Laser";
		mouse6.warranty = 3;
		mouse6.compatibility = "Mac";
		mouse6.isAvailable = false;
		mouse6.shape = "Compact";
		mouse6.cableLength = 1.3;

		mouse7.price = 1100;
		mouse7.type = "Gaming";
		mouse7.isWireless = true;
		mouse7.weight = 170;
		mouse7.sensorType = "Optical";
		mouse7.warranty = 2;
		mouse7.compatibility = "Windows";
		mouse7.isAvailable = true;
		mouse7.shape = "Ergonomic";
		mouse7.cableLength = 1.9;

		mouse8.price = 1200;
		mouse8.type = "Office";
		mouse8.isWireless = false;
		mouse8.weight = 125;
		mouse8.sensorType = "Laser";
		mouse8.warranty = 1;
		mouse8.compatibility = "Linux";
		mouse8.isAvailable = true;
		mouse8.shape = "Compact";
		mouse8.cableLength = 1.1;

		mouse9.price = 1300;
		mouse9.type = "Gaming";
		mouse9.isWireless = true;
		mouse9.weight = 165;
		mouse9.sensorType = "Optical";
		mouse9.warranty = 2;
		mouse9.compatibility = "Windows";
		mouse9.isAvailable = false;
		mouse9.shape = "Ergonomic";
		mouse9.cableLength = 2.0;

		mouse10.price = 1400;
		mouse10.type = "Office";
		mouse10.isWireless = false;
		mouse10.weight = 120;
		mouse10.sensorType = "Laser";
		mouse10.warranty = 3;
		mouse10.compatibility = "Mac";
		mouse10.isAvailable = true;
		mouse10.shape = "Compact";
		mouse10.cableLength = 1.4;

        System.out.println("\nMouse1 Details");
        System.out.println("Brand: " + mouse1.brand);
        System.out.println("Color: " + mouse1.color);
        System.out.println("Buttons: " + mouse1.buttons);
        System.out.println("Connection: " + mouse1.connection);
        System.out.println("DPI: " + mouse1.dpi);
        System.out.println("Price: " + mouse1.price);
        System.out.println("Type: " + mouse1.type);
        System.out.println("Wireless: " + mouse1.isWireless);
        System.out.println("Weight: " + mouse1.weight);
        System.out.println("Sensor: " + mouse1.sensorType);
        System.out.println("Warranty: " + mouse1.warranty);
        System.out.println("Compatibility: " + mouse1.compatibility);
        System.out.println("Available: " + mouse1.isAvailable);
        System.out.println("Shape: " + mouse1.shape);
        System.out.println("Cable Length: " + mouse1.cableLength);

        System.out.println("\nMouse2 Details");
        System.out.println("Brand: " + mouse2.brand);
        System.out.println("Color: " + mouse2.color);
        System.out.println("Buttons: " + mouse2.buttons);
        System.out.println("Connection: " + mouse2.connection);
        System.out.println("DPI: " + mouse2.dpi);
        System.out.println("Price: " + mouse2.price);
        System.out.println("Type: " + mouse2.type);
        System.out.println("Wireless: " + mouse2.isWireless);
        System.out.println("Weight: " + mouse2.weight);
        System.out.println("Sensor: " + mouse2.sensorType);
        System.out.println("Warranty: " + mouse2.warranty);
        System.out.println("Compatibility: " + mouse2.compatibility);
        System.out.println("Available: " + mouse2.isAvailable);
        System.out.println("Shape: " + mouse2.shape);
        System.out.println("Cable Length: " + mouse2.cableLength);

        System.out.println("\nMouse3 Details");
        System.out.println("Brand: " + mouse3.brand);
        System.out.println("Color: " + mouse3.color);
        System.out.println("Buttons: " + mouse3.buttons);
        System.out.println("Connection: " + mouse3.connection);
        System.out.println("DPI: " + mouse3.dpi);
        System.out.println("Price: " + mouse3.price);
        System.out.println("Type: " + mouse3.type);
        System.out.println("Wireless: " + mouse3.isWireless);
        System.out.println("Weight: " + mouse3.weight);
        System.out.println("Sensor: " + mouse3.sensorType);
        System.out.println("Warranty: " + mouse3.warranty);
        System.out.println("Compatibility: " + mouse3.compatibility);
        System.out.println("Available: " + mouse3.isAvailable);
        System.out.println("Shape: " + mouse3.shape);
        System.out.println("Cable Length: " + mouse3.cableLength);

        System.out.println("\nMouse4 Details");
        System.out.println("Brand: " + mouse4.brand);
        System.out.println("Color: " + mouse4.color);
        System.out.println("Buttons: " + mouse4.buttons);
        System.out.println("Connection: " + mouse4.connection);
        System.out.println("DPI: " + mouse4.dpi);
        System.out.println("Price: " + mouse4.price);
        System.out.println("Type: " + mouse4.type);
        System.out.println("Wireless: " + mouse4.isWireless);
        System.out.println("Weight: " + mouse4.weight);
        System.out.println("Sensor: " + mouse4.sensorType);
        System.out.println("Warranty: " + mouse4.warranty);
        System.out.println("Compatibility: " + mouse4.compatibility);
        System.out.println("Available: " + mouse4.isAvailable);
        System.out.println("Shape: " + mouse4.shape);
        System.out.println("Cable Length: " + mouse4.cableLength);

        System.out.println("\nMouse5 Details");
        System.out.println("Brand: " + mouse5.brand);
        System.out.println("Color: " + mouse5.color);
        System.out.println("Buttons: " + mouse5.buttons);
        System.out.println("Connection: " + mouse5.connection);
        System.out.println("DPI: " + mouse5.dpi);
        System.out.println("Price: " + mouse5.price);
        System.out.println("Type: " + mouse5.type);
        System.out.println("Wireless: " + mouse5.isWireless);
        System.out.println("Weight: " + mouse5.weight);
        System.out.println("Sensor: " + mouse5.sensorType);
        System.out.println("Warranty: " + mouse5.warranty);
        System.out.println("Compatibility: " + mouse5.compatibility);
        System.out.println("Available: " + mouse5.isAvailable);
        System.out.println("Shape: " + mouse5.shape);
        System.out.println("Cable Length: " + mouse5.cableLength);

        System.out.println("\nMouse6 Details");
        System.out.println("Brand: " + mouse6.brand);
        System.out.println("Color: " + mouse6.color);
        System.out.println("Buttons: " + mouse6.buttons);
        System.out.println("Connection: " + mouse6.connection);
        System.out.println("DPI: " + mouse6.dpi);
        System.out.println("Price: " + mouse6.price);
        System.out.println("Type: " + mouse6.type);
        System.out.println("Wireless: " + mouse6.isWireless);
        System.out.println("Weight: " + mouse6.weight);
        System.out.println("Sensor: " + mouse6.sensorType);
        System.out.println("Warranty: " + mouse6.warranty);
        System.out.println("Compatibility: " + mouse6.compatibility);
        System.out.println("Available: " + mouse6.isAvailable);
        System.out.println("Shape: " + mouse6.shape);
        System.out.println("Cable Length: " + mouse6.cableLength);

        System.out.println("\nMouse7 Details");
        System.out.println("Brand: " + mouse7.brand);
        System.out.println("Color: " + mouse7.color);
        System.out.println("Buttons: " + mouse7.buttons);
        System.out.println("Connection: " + mouse7.connection);
        System.out.println("DPI: " + mouse7.dpi);
        System.out.println("Price: " + mouse7.price);
        System.out.println("Type: " + mouse7.type);
        System.out.println("Wireless: " + mouse7.isWireless);
        System.out.println("Weight: " + mouse7.weight);
        System.out.println("Sensor: " + mouse7.sensorType);
        System.out.println("Warranty: " + mouse7.warranty);
        System.out.println("Compatibility: " + mouse7.compatibility);
        System.out.println("Available: " + mouse7.isAvailable);
        System.out.println("Shape: " + mouse7.shape);
        System.out.println("Cable Length: " + mouse7.cableLength);

        System.out.println("\nMouse8 Details");
        System.out.println("Brand: " + mouse8.brand);
        System.out.println("Color: " + mouse8.color);
        System.out.println("Buttons: " + mouse8.buttons);
        System.out.println("Connection: " + mouse8.connection);
        System.out.println("DPI: " + mouse8.dpi);
        System.out.println("Price: " + mouse8.price);
        System.out.println("Type: " + mouse8.type);
        System.out.println("Wireless: " + mouse8.isWireless);
        System.out.println("Weight: " + mouse8.weight);
        System.out.println("Sensor: " + mouse8.sensorType);
        System.out.println("Warranty: " + mouse8.warranty);
        System.out.println("Compatibility: " + mouse8.compatibility);
        System.out.println("Available: " + mouse8.isAvailable);
        System.out.println("Shape: " + mouse8.shape);
        System.out.println("Cable Length: " + mouse8.cableLength);

        System.out.println("\nMouse9 Details");
        System.out.println("Brand: " + mouse9.brand);
        System.out.println("Color: " + mouse9.color);
        System.out.println("Buttons: " + mouse9.buttons);
        System.out.println("Connection: " + mouse9.connection);
        System.out.println("DPI: " + mouse9.dpi);
        System.out.println("Price: " + mouse9.price);
        System.out.println("Type: " + mouse9.type);
        System.out.println("Wireless: " + mouse9.isWireless);
        System.out.println("Weight: " + mouse9.weight);
        System.out.println("Sensor: " + mouse9.sensorType);
        System.out.println("Warranty: " + mouse9.warranty);
        System.out.println("Compatibility: " + mouse9.compatibility);
        System.out.println("Available: " + mouse9.isAvailable);
        System.out.println("Shape: " + mouse9.shape);
        System.out.println("Cable Length: " + mouse9.cableLength);

        System.out.println("\nMouse10 Details");
        System.out.println("Brand: " + mouse10.brand);
        System.out.println("Color: " + mouse10.color);
        System.out.println("Buttons: " + mouse10.buttons);
        System.out.println("Connection: " + mouse10.connection);
        System.out.println("DPI: " + mouse10.dpi);
        System.out.println("Price: " + mouse10.price);
        System.out.println("Type: " + mouse10.type);
        System.out.println("Wireless: " + mouse10.isWireless);
        System.out.println("Weight: " + mouse10.weight);
        System.out.println("Sensor: " + mouse10.sensorType);
        System.out.println("Warranty: " + mouse10.warranty);
        System.out.println("Compatibility: " + mouse10.compatibility);
        System.out.println("Available: " + mouse10.isAvailable);
        System.out.println("Shape: " + mouse10.shape);
        System.out.println("Cable Length: " + mouse10.cableLength);

    }
}