class RouterRunner {

    public static void main(String[] args) {

        Router r1 = new Router();
        Router r2 = new Router();
        Router r3 = new Router();
        Router r4 = new Router();
        Router r5 = new Router();
        Router r6 = new Router();
        Router r7 = new Router();
        Router r8 = new Router();
        Router r9 = new Router();
        Router r10 = new Router();

        r1.price = 1500;
        r1.model = "Archer C20";
        r1.speed = 750;
        r1.frequency = "2.4GHz/5GHz";
        r1.security = "WPA2";
        r1.isAvailable = true;
        r1.warranty = 2;
        r1.connectivity = "WiFi";
        r1.weight = 0.5;
        r1.compatibility = "Home";

        r2.price = 2500;
        r2.model = "Archer C50";
        r2.speed = 1200;
        r2.frequency = "Dual Band";
        r2.security = "WPA2/WPA3";
        r2.isAvailable = true;
        r2.warranty = 3;
        r2.connectivity = "WiFi";
        r2.weight = 0.6;
        r2.compatibility = "Home";

        r3.price = 3000;
        r3.model = "Archer A6";
        r3.speed = 1200;
        r3.frequency = "Dual Band";
        r3.security = "WPA3";
        r3.isAvailable = true;
        r3.warranty = 3;
        r3.connectivity = "WiFi";
        r3.weight = 0.7;
        r3.compatibility = "Office";

        r4.price = 4000;
        r4.model = "Archer A7";
        r4.speed = 1750;
        r4.frequency = "Dual Band";
        r4.security = "WPA3";
        r4.isAvailable = true;
        r4.warranty = 4;
        r4.connectivity = "WiFi";
        r4.weight = 0.8;
        r4.compatibility = "Office";

        r5.price = 5000;
        r5.model = "Archer AX10";
        r5.speed = 1500;
        r5.frequency = "WiFi 6";
        r5.security = "WPA3";
        r5.isAvailable = true;
        r5.warranty = 4;
        r5.connectivity = "WiFi";
        r5.weight = 0.9;
        r5.compatibility = "Home";

        r6.price = 6000;
        r6.model = "Archer AX20";
        r6.speed = 1800;
        r6.frequency = "WiFi 6";
        r6.security = "WPA3";
        r6.isAvailable = true;
        r6.warranty = 5;
        r6.connectivity = "WiFi";
        r6.weight = 1.0;
        r6.compatibility = "Office";

        r7.price = 2000;
        r7.model = "TL-WR841N";
        r7.speed = 300;
        r7.frequency = "2.4GHz";
        r7.security = "WPA2";
        r7.isAvailable = false;
        r7.warranty = 2;
        r7.connectivity = "WiFi";
        r7.weight = 0.4;
        r7.compatibility = "Home";

        r8.price = 3500;
        r8.model = "Archer C80";
        r8.speed = 1900;
        r8.frequency = "Dual Band";
        r8.security = "WPA3";
        r8.isAvailable = true;
        r8.warranty = 3;
        r8.connectivity = "WiFi";
        r8.weight = 0.85;
        r8.compatibility = "Office";

        r9.price = 7000;
        r9.model = "Archer AX50";
        r9.speed = 3000;
        r9.frequency = "WiFi 6";
        r9.security = "WPA3";
        r9.isAvailable = true;
        r9.warranty = 5;
        r9.connectivity = "WiFi";
        r9.weight = 1.1;
        r9.compatibility = "Office";

        r10.price = 8000;
        r10.model = "Archer AX73";
        r10.speed = 5400;
        r10.frequency = "WiFi 6";
        r10.security = "WPA3";
        r10.isAvailable = true;
        r10.warranty = 5;
        r10.connectivity = "WiFi";
        r10.weight = 1.2;
        r10.compatibility = "Enterprise";


        System.out.println("\nRouter1 Details");
        System.out.println("Brand: " + r1.brand);
        System.out.println("Color: " + r1.color);
        System.out.println("Type: " + r1.type);
        System.out.println("Dual Band: " + r1.supportsDualBand);
        System.out.println("Antennas: " + r1.antennas);
        System.out.println("Price: " + r1.price);
        System.out.println("Model: " + r1.model);
        System.out.println("Speed: " + r1.speed);
        System.out.println("Frequency: " + r1.frequency);
        System.out.println("Security: " + r1.security);
        System.out.println("Available: " + r1.isAvailable);
        System.out.println("Warranty: " + r1.warranty);
        System.out.println("Connectivity: " + r1.connectivity);
        System.out.println("Weight: " + r1.weight);
        System.out.println("Compatibility: " + r1.compatibility);

        System.out.println("\nRouter2 Details");
        System.out.println("Brand: " + r2.brand);
        System.out.println("Color: " + r2.color);
        System.out.println("Type: " + r2.type);
        System.out.println("Dual Band: " + r2.supportsDualBand);
        System.out.println("Antennas: " + r2.antennas);
        System.out.println("Price: " + r2.price);
        System.out.println("Model: " + r2.model);
        System.out.println("Speed: " + r2.speed);
        System.out.println("Frequency: " + r2.frequency);
        System.out.println("Security: " + r2.security);
        System.out.println("Available: " + r2.isAvailable);
        System.out.println("Warranty: " + r2.warranty);
        System.out.println("Connectivity: " + r2.connectivity);
        System.out.println("Weight: " + r2.weight);
        System.out.println("Compatibility: " + r2.compatibility);

                System.out.println("\nRouter3 Details");
        System.out.println("Brand: " + r3.brand);
        System.out.println("Color: " + r3.color);
        System.out.println("Type: " + r3.type);
        System.out.println("Dual Band: " + r3.supportsDualBand);
        System.out.println("Antennas: " + r3.antennas);
        System.out.println("Price: " + r3.price);
        System.out.println("Model: " + r3.model);
        System.out.println("Speed: " + r3.speed);
        System.out.println("Frequency: " + r3.frequency);
        System.out.println("Security: " + r3.security);
        System.out.println("Available: " + r3.isAvailable);
        System.out.println("Warranty: " + r3.warranty);
        System.out.println("Connectivity: " + r3.connectivity);
        System.out.println("Weight: " + r3.weight);
        System.out.println("Compatibility: " + r3.compatibility);

        System.out.println("\nRouter4 Details");
        System.out.println("Brand: " + r4.brand);
        System.out.println("Color: " + r4.color);
        System.out.println("Type: " + r4.type);
        System.out.println("Dual Band: " + r4.supportsDualBand);
        System.out.println("Antennas: " + r4.antennas);
        System.out.println("Price: " + r4.price);
        System.out.println("Model: " + r4.model);
        System.out.println("Speed: " + r4.speed);
        System.out.println("Frequency: " + r4.frequency);
        System.out.println("Security: " + r4.security);
        System.out.println("Available: " + r4.isAvailable);
        System.out.println("Warranty: " + r4.warranty);
        System.out.println("Connectivity: " + r4.connectivity);
        System.out.println("Weight: " + r4.weight);
        System.out.println("Compatibility: " + r4.compatibility);

        System.out.println("\nRouter5 Details");
        System.out.println("Brand: " + r5.brand);
        System.out.println("Color: " + r5.color);
        System.out.println("Type: " + r5.type);
        System.out.println("Dual Band: " + r5.supportsDualBand);
        System.out.println("Antennas: " + r5.antennas);
        System.out.println("Price: " + r5.price);
        System.out.println("Model: " + r5.model);
        System.out.println("Speed: " + r5.speed);
        System.out.println("Frequency: " + r5.frequency);
        System.out.println("Security: " + r5.security);
        System.out.println("Available: " + r5.isAvailable);
        System.out.println("Warranty: " + r5.warranty);
        System.out.println("Connectivity: " + r5.connectivity);
        System.out.println("Weight: " + r5.weight);
        System.out.println("Compatibility: " + r5.compatibility);

        System.out.println("\nRouter6 Details");
        System.out.println("Brand: " + r6.brand);
        System.out.println("Color: " + r6.color);
        System.out.println("Type: " + r6.type);
        System.out.println("Dual Band: " + r6.supportsDualBand);
        System.out.println("Antennas: " + r6.antennas);
        System.out.println("Price: " + r6.price);
        System.out.println("Model: " + r6.model);
        System.out.println("Speed: " + r6.speed);
        System.out.println("Frequency: " + r6.frequency);
        System.out.println("Security: " + r6.security);
        System.out.println("Available: " + r6.isAvailable);
        System.out.println("Warranty: " + r6.warranty);
        System.out.println("Connectivity: " + r6.connectivity);
        System.out.println("Weight: " + r6.weight);
        System.out.println("Compatibility: " + r6.compatibility);

        System.out.println("\nRouter7 Details");
        System.out.println("Brand: " + r7.brand);
        System.out.println("Color: " + r7.color);
        System.out.println("Type: " + r7.type);
        System.out.println("Dual Band: " + r7.supportsDualBand);
        System.out.println("Antennas: " + r7.antennas);
        System.out.println("Price: " + r7.price);
        System.out.println("Model: " + r7.model);
        System.out.println("Speed: " + r7.speed);
        System.out.println("Frequency: " + r7.frequency);
        System.out.println("Security: " + r7.security);
        System.out.println("Available: " + r7.isAvailable);
        System.out.println("Warranty: " + r7.warranty);
        System.out.println("Connectivity: " + r7.connectivity);
        System.out.println("Weight: " + r7.weight);
        System.out.println("Compatibility: " + r7.compatibility);

        System.out.println("\nRouter8 Details");
        System.out.println("Brand: " + r8.brand);
        System.out.println("Color: " + r8.color);
        System.out.println("Type: " + r8.type);
        System.out.println("Dual Band: " + r8.supportsDualBand);
        System.out.println("Antennas: " + r8.antennas);
        System.out.println("Price: " + r8.price);
        System.out.println("Model: " + r8.model);
        System.out.println("Speed: " + r8.speed);
        System.out.println("Frequency: " + r8.frequency);
        System.out.println("Security: " + r8.security);
        System.out.println("Available: " + r8.isAvailable);
        System.out.println("Warranty: " + r8.warranty);
        System.out.println("Connectivity: " + r8.connectivity);
        System.out.println("Weight: " + r8.weight);
        System.out.println("Compatibility: " + r8.compatibility);

        System.out.println("\nRouter9 Details");
        System.out.println("Brand: " + r9.brand);
        System.out.println("Color: " + r9.color);
        System.out.println("Type: " + r9.type);
        System.out.println("Dual Band: " + r9.supportsDualBand);
        System.out.println("Antennas: " + r9.antennas);
        System.out.println("Price: " + r9.price);
        System.out.println("Model: " + r9.model);
        System.out.println("Speed: " + r9.speed);
        System.out.println("Frequency: " + r9.frequency);
        System.out.println("Security: " + r9.security);
        System.out.println("Available: " + r9.isAvailable);
        System.out.println("Warranty: " + r9.warranty);
        System.out.println("Connectivity: " + r9.connectivity);
        System.out.println("Weight: " + r9.weight);
        System.out.println("Compatibility: " + r9.compatibility);

        System.out.println("\nRouter10 Details");
        System.out.println("Brand: " + r10.brand);
        System.out.println("Color: " + r10.color);
        System.out.println("Type: " + r10.type);
        System.out.println("Dual Band: " + r10.supportsDualBand);
        System.out.println("Antennas: " + r10.antennas);
        System.out.println("Price: " + r10.price);
        System.out.println("Model: " + r10.model);
        System.out.println("Speed: " + r10.speed);
        System.out.println("Frequency: " + r10.frequency);
        System.out.println("Security: " + r10.security);
        System.out.println("Available: " + r10.isAvailable);
        System.out.println("Warranty: " + r10.warranty);
        System.out.println("Connectivity: " + r10.connectivity);
        System.out.println("Weight: " + r10.weight);
        System.out.println("Compatibility: " + r10.compatibility);
    }
}