class CabinetRunner{
	public static void main(String[] args){
		Cabinet cabinet1=new Cabinet();
	    Cabinet cabinet2=new Cabinet();
		Cabinet cabinet3=new Cabinet();
		Cabinet cabinet4=new Cabinet();
		Cabinet cabinet5=new Cabinet();
		Cabinet cabinet6=new Cabinet();
		Cabinet cabinet7=new Cabinet();
		Cabinet cabinet8=new Cabinet();
		Cabinet cabinet9=new Cabinet();
	    Cabinet cabinet10=new Cabinet();
		cabinet1.weight=100;
		cabinet1.height=60;
		cabinet1.noOfShelves=15;
		cabinet1.doorType = "Sliding";
		cabinet1.lockType="numeric";
		cabinet1.price = 1000.0;
		cabinet1.brand = "tanu";
		cabinet1.finish = "matte";
		cabinet1.capacity = 80;
		cabinet1.isAvailable = true;
		
		System.out.println("\nCabinet1 details\n");
		System.out.println("Material: " + cabinet1.material);
		System.out.println("Color: " + cabinet1.color);
		System.out.println("Width: " + cabinet1.width);
		System.out.println("Depth: " + cabinet1.depth);
		System.out.println("No of Doors: " + cabinet1.noOfDoors);
		System.out.println("Weight: " + cabinet1.weight);
		System.out.println("Height: " + cabinet1.height);
		System.out.println("No of Shelves: " + cabinet1.noOfShelves);
		System.out.println("Door Type: " + cabinet1.doorType);
		System.out.println("Lock Type: " + cabinet1.lockType);
		System.out.println("Price: " + cabinet1.price);
		System.out.println("Brand: " + cabinet1.brand);
		System.out.println("Finish: " + cabinet1.finish);
		System.out.println("Capacity: " + cabinet1.capacity);
		System.out.println("Available: " + cabinet1.isAvailable); 		
		
		cabinet2.weight = 120;
		cabinet2.height = 65;
		cabinet2.noOfShelves = 10;
		cabinet2.doorType = "Hinged";
		cabinet2.lockType = "key";
		cabinet2.price = 1500.0;
		cabinet2.brand = "woodCraft";
		cabinet2.finish = "glossy";
		cabinet2.capacity = 100;
		cabinet2.isAvailable = false;
        System.out.println("\nCabinet2 details\n");
		System.out.println("Material: " + cabinet2.material);
		System.out.println("Color: " + cabinet2.color);
		System.out.println("Width: " + cabinet2.width);
		System.out.println("Depth: " + cabinet2.depth);
		System.out.println("No of Doors: " + cabinet2.noOfDoors);
		System.out.println("Weight: " + cabinet2.weight);
		System.out.println("Height: " + cabinet2.height);
		System.out.println("No of Shelves: " + cabinet2.noOfShelves);
		System.out.println("Door Type: " + cabinet2.doorType);
		System.out.println("Lock Type: " + cabinet2.lockType);
		System.out.println("Price: " + cabinet2.price);
		System.out.println("Brand: " + cabinet2.brand);
		System.out.println("Finish: " + cabinet2.finish);
		System.out.println("Capacity: " + cabinet2.capacity);
		System.out.println("Available: " + cabinet2.isAvailable);		
		
		cabinet3.weight = 90;
		cabinet3.height = 55;
		cabinet3.noOfShelves = 8;
		cabinet3.doorType = "Sliding";
		cabinet3.lockType = "digital";
		cabinet3.price = 2000.0;
		cabinet3.brand = "furniHome";
		cabinet3.finish = "matte";
		cabinet3.capacity = 70;
		cabinet3.isAvailable = true;
		
		System.out.println("\nCabinet3 details\n");
		System.out.println("Material: " + cabinet3.material);
		System.out.println("Color: " + cabinet3.color);
		System.out.println("Width: " + cabinet3.width);
		System.out.println("Depth: " + cabinet3.depth);
		System.out.println("No of Doors: " + cabinet3.noOfDoors);
		System.out.println("Weight: " + cabinet3.weight);
		System.out.println("Height: " + cabinet3.height);
		System.out.println("No of Shelves: " + cabinet3.noOfShelves);
		System.out.println("Door Type: " + cabinet3.doorType);
		System.out.println("Lock Type: " + cabinet3.lockType);
		System.out.println("Price: " + cabinet3.price);
		System.out.println("Brand: " + cabinet3.brand);
		System.out.println("Finish: " + cabinet3.finish);
		System.out.println("Capacity: " + cabinet3.capacity);
		System.out.println("Available: " + cabinet3.isAvailable);
			
			
	    cabinet4.weight = 140;
		cabinet4.height = 75;
		cabinet4.noOfShelves = 12;
		cabinet4.doorType = "Hinged";
		cabinet4.lockType = "numeric";
		cabinet4.price = 2500.0;
		cabinet4.brand = "elite";
		cabinet4.finish = "polished";
		cabinet4.capacity = 130;
		cabinet4.isAvailable = true;
		System.out.println("\nCabinet4 details\n");
		System.out.println("Material: " + cabinet4.material);
		System.out.println("Color: " + cabinet4.color);
		System.out.println("Width: " + cabinet4.width);
		System.out.println("Depth: " + cabinet4.depth);
		System.out.println("No of Doors: " + cabinet4.noOfDoors);
		System.out.println("Weight: " + cabinet4.weight);
		System.out.println("Height: " + cabinet4.height);
		System.out.println("No of Shelves: " + cabinet4.noOfShelves);
		System.out.println("Door Type: " + cabinet4.doorType);
		System.out.println("Lock Type: " + cabinet4.lockType);
		System.out.println("Price: " + cabinet4.price);
		System.out.println("Brand: " + cabinet4.brand);
		System.out.println("Finish: " + cabinet4.finish);
		System.out.println("Capacity: " + cabinet4.capacity);
		System.out.println("Available: " + cabinet4.isAvailable);
		
		cabinet5.weight = 110;
		cabinet5.height = 68;
		cabinet5.noOfShelves = 9;
		cabinet5.doorType = "Sliding";
		cabinet5.lockType = "key";
		cabinet5.price = 1800.0;
		cabinet5.brand = "urbanWood";
		cabinet5.finish = "matte";
		cabinet5.capacity = 95;
		cabinet5.isAvailable = false;
		System.out.println("\nCabinet5 details\n");
		System.out.println("Material: " + cabinet5.material);
		System.out.println("Color: " + cabinet5.color);
		System.out.println("Width: " + cabinet5.width);
		System.out.println("Depth: " + cabinet5.depth);
		System.out.println("No of Doors: " + cabinet5.noOfDoors);
		System.out.println("Weight: " + cabinet5.weight);
		System.out.println("Height: " + cabinet5.height);
		System.out.println("No of Shelves: " + cabinet5.noOfShelves);
		System.out.println("Door Type: " + cabinet5.doorType);
		System.out.println("Lock Type: " + cabinet5.lockType);
		System.out.println("Price: " + cabinet5.price);
		System.out.println("Brand: " + cabinet5.brand);
		System.out.println("Finish: " + cabinet5.finish);
		System.out.println("Capacity: " + cabinet5.capacity);
		System.out.println("Available: " + cabinet5.isAvailable);
		
		cabinet6.weight = 160;
		cabinet6.height = 80;
		cabinet6.noOfShelves = 14;
		cabinet6.doorType = "Hinged";
		cabinet6.lockType = "biometric";
		cabinet6.price = 3000.0;
		cabinet6.brand = "secureHome";
		cabinet6.finish = "glossy";
		cabinet6.capacity = 150;
		cabinet6.isAvailable = true;
		System.out.println("\nCabinet6 details\n");
		System.out.println("Material: " + cabinet6.material);
		System.out.println("Color: " + cabinet6.color);
		System.out.println("Width: " + cabinet6.width);
		System.out.println("Depth: " + cabinet6.depth);
		System.out.println("No of Doors: " + cabinet6.noOfDoors);
		System.out.println("Weight: " + cabinet6.weight);
		System.out.println("Height: " + cabinet6.height);
		System.out.println("No of Shelves: " + cabinet6.noOfShelves);
		System.out.println("Door Type: " + cabinet6.doorType);
		System.out.println("Lock Type: " + cabinet6.lockType);
		System.out.println("Price: " + cabinet6.price);
		System.out.println("Brand: " + cabinet6.brand);
		System.out.println("Finish: " + cabinet6.finish);
		System.out.println("Capacity: " + cabinet6.capacity);
		System.out.println("Available: " + cabinet6.isAvailable);
				
		
		cabinet7.weight = 85;
		cabinet7.height = 50;
		cabinet7.noOfShelves = 6;
		cabinet7.doorType = "Sliding";
		cabinet7.lockType = "key";
		cabinet7.price = 1200.0;
		cabinet7.brand = "basic";
		cabinet7.finish = "rough";
		cabinet7.capacity = 60;
		cabinet7.isAvailable = true;
		System.out.println("\nCabinet7 details\n");
		System.out.println("Material: " + cabinet7.material);
		System.out.println("Color: " + cabinet7.color);
		System.out.println("Width: " + cabinet7.width);
		System.out.println("Depth: " + cabinet7.depth);
		System.out.println("No of Doors: " + cabinet7.noOfDoors);
		System.out.println("Weight: " + cabinet7.weight);
		System.out.println("Height: " + cabinet7.height);
		System.out.println("No of Shelves: " + cabinet7.noOfShelves);
		System.out.println("Door Type: " + cabinet7.doorType);
		System.out.println("Lock Type: " + cabinet7.lockType);
		System.out.println("Price: " + cabinet7.price);
		System.out.println("Brand: " + cabinet7.brand);
		System.out.println("Finish: " + cabinet7.finish);
		System.out.println("Capacity: " + cabinet7.capacity);
		System.out.println("Available: " + cabinet7.isAvailable);
		
		cabinet8.weight = 130;
		cabinet8.height = 70;
		cabinet8.noOfShelves = 11;
		cabinet8.doorType = "Hinged";
		cabinet8.lockType = "digital";
		cabinet8.price = 2700.0;
		cabinet8.brand = "premium";
		cabinet8.finish = "polished";
		cabinet8.capacity = 120;
		cabinet8.isAvailable = false;
		System.out.println("\nCabinet8 details\n");
		System.out.println("Material: " + cabinet8.material);
		System.out.println("Color: " + cabinet8.color);
		System.out.println("Width: " + cabinet8.width);
		System.out.println("Depth: " + cabinet8.depth);
		System.out.println("No of Doors: " + cabinet8.noOfDoors);
		System.out.println("Weight: " + cabinet8.weight);
		System.out.println("Height: " + cabinet8.height);
		System.out.println("No of Shelves: " + cabinet8.noOfShelves);
		System.out.println("Door Type: " + cabinet8.doorType);
		System.out.println("Lock Type: " + cabinet8.lockType);
		System.out.println("Price: " + cabinet8.price);
		System.out.println("Brand: " + cabinet8.brand);
		System.out.println("Finish: " + cabinet8.finish);
		System.out.println("Capacity: " + cabinet8.capacity);
		System.out.println("Available: " + cabinet8.isAvailable);
		
		cabinet9.weight = 95;
		cabinet9.height = 60;
		cabinet9.noOfShelves = 7;
		cabinet9.doorType = "Sliding";
		cabinet9.lockType = "numeric";
		cabinet9.price = 1600.0;
		cabinet9.brand = "homeFit";
		cabinet9.finish = "matte";
		cabinet9.capacity = 85;
		cabinet9.isAvailable = true;
		System.out.println("\nCabinet9 details\n");
		System.out.println("Material: " + cabinet9.material);
		System.out.println("Color: " + cabinet9.color);
		System.out.println("Width: " + cabinet9.width);
		System.out.println("Depth: " + cabinet9.depth);
		System.out.println("No of Doors: " + cabinet9.noOfDoors);
		System.out.println("Weight: " + cabinet9.weight);
		System.out.println("Height: " + cabinet9.height);
		System.out.println("No of Shelves: " + cabinet9.noOfShelves);
		System.out.println("Door Type: " + cabinet9.doorType);
		System.out.println("Lock Type: " + cabinet9.lockType);
		System.out.println("Price: " + cabinet9.price);
		System.out.println("Brand: " + cabinet9.brand);
		System.out.println("Finish: " + cabinet9.finish);
		System.out.println("Capacity: " + cabinet9.capacity);
		System.out.println("Available: " + cabinet9.isAvailable);
		
		
		cabinet10.weight = 170;
		cabinet10.height = 85;
		cabinet10.noOfShelves = 16;
		cabinet10.doorType = "Hinged";
		cabinet10.lockType = "biometric";
		cabinet10.price = 3500.0;
		cabinet10.brand = "luxuryLine";
		cabinet10.finish = "glossy";
		cabinet10.capacity = 180;
		cabinet10.isAvailable = true;
		System.out.println("\nCabinet10 details\n");
		System.out.println("Material: " + cabinet10.material);
		System.out.println("Color: " + cabinet10.color);
		System.out.println("Width: " + cabinet10.width);
		System.out.println("Depth: " + cabinet10.depth);
		System.out.println("No of Doors: " + cabinet10.noOfDoors);
		System.out.println("Weight: " + cabinet10.weight);
		System.out.println("Height: " + cabinet10.height);
		System.out.println("No of Shelves: " + cabinet10.noOfShelves);
		System.out.println("Door Type: " + cabinet10.doorType);
		System.out.println("Lock Type: " + cabinet10.lockType);
		System.out.println("Price: " + cabinet10.price);
		System.out.println("Brand: " + cabinet10.brand);
		System.out.println("Finish: " + cabinet10.finish);
		System.out.println("Capacity: " + cabinet10.capacity);
		System.out.println("Available: " + cabinet10.isAvailable);
										
			}
}






	