class ControllerRunner {

    public static void main(String[] args) {

        Controller c1 = new Controller();
        Controller c2 = new Controller();
        Controller c3 = new Controller();
        Controller c4 = new Controller();
        Controller c5 = new Controller();
        Controller c6 = new Controller();
        Controller c7 = new Controller();
        Controller c8 = new Controller();
        Controller c9 = new Controller();
        Controller c10 = new Controller();

        c1.price = 4000;
        c1.model = "DualShock 4";
        c1.buttons = 12;
        c1.weight = 0.3;
        c1.connectivity = "Bluetooth";
        c1.isAvailable = true;
        c1.warranty = 2;
        c1.compatibility = "PS4";
        c1.vibrationType = "Dual Motor";
        c1.chargingType = "Micro USB";

        c2.price = 6000;
        c2.model = "DualSense";
        c2.buttons = 14;
        c2.weight = 0.35;
        c2.connectivity = "Bluetooth";
        c2.isAvailable = true;
        c2.warranty = 2;
        c2.compatibility = "PS5";
        c2.vibrationType = "Haptic";
        c2.chargingType = "Type-C";

        c3.price = 3500;
        c3.model = "Xbox Controller";
        c3.buttons = 12;
        c3.weight = 0.32;
        c3.connectivity = "Wireless";
        c3.isAvailable = true;
        c3.warranty = 2;
        c3.compatibility = "Xbox";
        c3.vibrationType = "Dual Motor";
        c3.chargingType = "AA Battery";

        c4.price = 4500;
        c4.model = "Xbox Elite";
        c4.buttons = 16;
        c4.weight = 0.4;
        c4.connectivity = "Wireless";
        c4.isAvailable = true;
        c4.warranty = 3;
        c4.compatibility = "Xbox";
        c4.vibrationType = "Advanced";
        c4.chargingType = "Type-C";

        c5.price = 3000;
        c5.model = "Generic Pro";
        c5.buttons = 10;
        c5.weight = 0.28;
        c5.connectivity = "Wired";
        c5.isAvailable = true;
        c5.warranty = 1;
        c5.compatibility = "PC";
        c5.vibrationType = "Basic";
        c5.chargingType = "USB";

        c6.price = 5500;
        c6.model = "DualSense Edge";
        c6.buttons = 14;
        c6.weight = 0.36;
        c6.connectivity = "Bluetooth";
        c6.isAvailable = true;
        c6.warranty = 3;
        c6.compatibility = "PS5";
        c6.vibrationType = "Haptic";
        c6.chargingType = "Type-C";

        c7.price = 2500;
        c7.model = "Budget Pad";
        c7.buttons = 10;
        c7.weight = 0.27;
        c7.connectivity = "Wired";
        c7.isAvailable = false;
        c7.warranty = 1;
        c7.compatibility = "PC";
        c7.vibrationType = "Basic";
        c7.chargingType = "USB";

        c8.price = 4800;
        c8.model = "Pro Controller";
        c8.buttons = 12;
        c8.weight = 0.34;
        c8.connectivity = "Bluetooth";
        c8.isAvailable = true;
        c8.warranty = 2;
        c8.compatibility = "Switch";
        c8.vibrationType = "HD Rumble";
        c8.chargingType = "Type-C";

        c9.price = 7000;
        c9.model = "Elite Series 2";
        c9.buttons = 16;
        c9.weight = 0.42;
        c9.connectivity = "Wireless";
        c9.isAvailable = true;
        c9.warranty = 3;
        c9.compatibility = "Xbox";
        c9.vibrationType = "Advanced";
        c9.chargingType = "Type-C";

        c10.price = 2000;
        c10.model = "Mini Controller";
        c10.buttons = 8;
        c10.weight = 0.2;
        c10.connectivity = "Wired";
        c10.isAvailable = true;
        c10.warranty = 1;
        c10.compatibility = "Mobile";
        c10.vibrationType = "None";
        c10.chargingType = "USB";


        System.out.println("\nController1 Details");
        System.out.println("Brand: " + c1.brand);
        System.out.println("Color: " + c1.color);
        System.out.println("Type: " + c1.type);
        System.out.println("Wireless: " + c1.isWireless);
        System.out.println("Battery: " + c1.batteryCapacity);
        System.out.println("Price: " + c1.price);
        System.out.println("Model: " + c1.model);
        System.out.println("Buttons: " + c1.buttons);
        System.out.println("Weight: " + c1.weight);
        System.out.println("Connectivity: " + c1.connectivity);
        System.out.println("Available: " + c1.isAvailable);
        System.out.println("Warranty: " + c1.warranty);
        System.out.println("Compatibility: " + c1.compatibility);
        System.out.println("Vibration: " + c1.vibrationType);
        System.out.println("Charging: " + c1.chargingType);

        System.out.println("\nController2 Details");
        System.out.println("Brand: " + c2.brand);
        System.out.println("Color: " + c2.color);
        System.out.println("Type: " + c2.type);
        System.out.println("Wireless: " + c2.isWireless);
        System.out.println("Battery: " + c2.batteryCapacity);
        System.out.println("Price: " + c2.price);
        System.out.println("Model: " + c2.model);
        System.out.println("Buttons: " + c2.buttons);
        System.out.println("Weight: " + c2.weight);
        System.out.println("Connectivity: " + c2.connectivity);
        System.out.println("Available: " + c2.isAvailable);
        System.out.println("Warranty: " + c2.warranty);
        System.out.println("Compatibility: " + c2.compatibility);
        System.out.println("Vibration: " + c2.vibrationType);
        System.out.println("Charging: " + c2.chargingType);

               System.out.println("\nController3 Details");
        System.out.println("Brand: " + c3.brand);
        System.out.println("Color: " + c3.color);
        System.out.println("Type: " + c3.type);
        System.out.println("Wireless: " + c3.isWireless);
        System.out.println("Battery: " + c3.batteryCapacity);
        System.out.println("Price: " + c3.price);
        System.out.println("Model: " + c3.model);
        System.out.println("Buttons: " + c3.buttons);
        System.out.println("Weight: " + c3.weight);
        System.out.println("Connectivity: " + c3.connectivity);
        System.out.println("Available: " + c3.isAvailable);
        System.out.println("Warranty: " + c3.warranty);
        System.out.println("Compatibility: " + c3.compatibility);
        System.out.println("Vibration: " + c3.vibrationType);
        System.out.println("Charging: " + c3.chargingType);

        System.out.println("\nController4 Details");
        System.out.println("Brand: " + c4.brand);
        System.out.println("Color: " + c4.color);
        System.out.println("Type: " + c4.type);
        System.out.println("Wireless: " + c4.isWireless);
        System.out.println("Battery: " + c4.batteryCapacity);
        System.out.println("Price: " + c4.price);
        System.out.println("Model: " + c4.model);
        System.out.println("Buttons: " + c4.buttons);
        System.out.println("Weight: " + c4.weight);
        System.out.println("Connectivity: " + c4.connectivity);
        System.out.println("Available: " + c4.isAvailable);
        System.out.println("Warranty: " + c4.warranty);
        System.out.println("Compatibility: " + c4.compatibility);
        System.out.println("Vibration: " + c4.vibrationType);
        System.out.println("Charging: " + c4.chargingType);

        System.out.println("\nController5 Details");
        System.out.println("Brand: " + c5.brand);
        System.out.println("Color: " + c5.color);
        System.out.println("Type: " + c5.type);
        System.out.println("Wireless: " + c5.isWireless);
        System.out.println("Battery: " + c5.batteryCapacity);
        System.out.println("Price: " + c5.price);
        System.out.println("Model: " + c5.model);
        System.out.println("Buttons: " + c5.buttons);
        System.out.println("Weight: " + c5.weight);
        System.out.println("Connectivity: " + c5.connectivity);
        System.out.println("Available: " + c5.isAvailable);
        System.out.println("Warranty: " + c5.warranty);
        System.out.println("Compatibility: " + c5.compatibility);
        System.out.println("Vibration: " + c5.vibrationType);
        System.out.println("Charging: " + c5.chargingType);

        System.out.println("\nController6 Details");
        System.out.println("Brand: " + c6.brand);
        System.out.println("Color: " + c6.color);
        System.out.println("Type: " + c6.type);
        System.out.println("Wireless: " + c6.isWireless);
        System.out.println("Battery: " + c6.batteryCapacity);
        System.out.println("Price: " + c6.price);
        System.out.println("Model: " + c6.model);
        System.out.println("Buttons: " + c6.buttons);
        System.out.println("Weight: " + c6.weight);
        System.out.println("Connectivity: " + c6.connectivity);
        System.out.println("Available: " + c6.isAvailable);
        System.out.println("Warranty: " + c6.warranty);
        System.out.println("Compatibility: " + c6.compatibility);
        System.out.println("Vibration: " + c6.vibrationType);
        System.out.println("Charging: " + c6.chargingType);

        System.out.println("\nController7 Details");
        System.out.println("Brand: " + c7.brand);
        System.out.println("Color: " + c7.color);
        System.out.println("Type: " + c7.type);
        System.out.println("Wireless: " + c7.isWireless);
        System.out.println("Battery: " + c7.batteryCapacity);
        System.out.println("Price: " + c7.price);
        System.out.println("Model: " + c7.model);
        System.out.println("Buttons: " + c7.buttons);
        System.out.println("Weight: " + c7.weight);
        System.out.println("Connectivity: " + c7.connectivity);
        System.out.println("Available: " + c7.isAvailable);
        System.out.println("Warranty: " + c7.warranty);
        System.out.println("Compatibility: " + c7.compatibility);
        System.out.println("Vibration: " + c7.vibrationType);
        System.out.println("Charging: " + c7.chargingType);

        System.out.println("\nController8 Details");
        System.out.println("Brand: " + c8.brand);
        System.out.println("Color: " + c8.color);
        System.out.println("Type: " + c8.type);
        System.out.println("Wireless: " + c8.isWireless);
        System.out.println("Battery: " + c8.batteryCapacity);
        System.out.println("Price: " + c8.price);
        System.out.println("Model: " + c8.model);
        System.out.println("Buttons: " + c8.buttons);
        System.out.println("Weight: " + c8.weight);
        System.out.println("Connectivity: " + c8.connectivity);
        System.out.println("Available: " + c8.isAvailable);
        System.out.println("Warranty: " + c8.warranty);
        System.out.println("Compatibility: " + c8.compatibility);
        System.out.println("Vibration: " + c8.vibrationType);
        System.out.println("Charging: " + c8.chargingType);

        System.out.println("\nController9 Details");
        System.out.println("Brand: " + c9.brand);
        System.out.println("Color: " + c9.color);
        System.out.println("Type: " + c9.type);
        System.out.println("Wireless: " + c9.isWireless);
        System.out.println("Battery: " + c9.batteryCapacity);
        System.out.println("Price: " + c9.price);
        System.out.println("Model: " + c9.model);
        System.out.println("Buttons: " + c9.buttons);
        System.out.println("Weight: " + c9.weight);
        System.out.println("Connectivity: " + c9.connectivity);
        System.out.println("Available: " + c9.isAvailable);
        System.out.println("Warranty: " + c9.warranty);
        System.out.println("Compatibility: " + c9.compatibility);
        System.out.println("Vibration: " + c9.vibrationType);
        System.out.println("Charging: " + c9.chargingType);

        System.out.println("\nController10 Details");
        System.out.println("Brand: " + c10.brand);
        System.out.println("Color: " + c10.color);
        System.out.println("Type: " + c10.type);
        System.out.println("Wireless: " + c10.isWireless);
        System.out.println("Battery: " + c10.batteryCapacity);
        System.out.println("Price: " + c10.price);
        System.out.println("Model: " + c10.model);
        System.out.println("Buttons: " + c10.buttons);
        System.out.println("Weight: " + c10.weight);
        System.out.println("Connectivity: " + c10.connectivity);
        System.out.println("Available: " + c10.isAvailable);
        System.out.println("Warranty: " + c10.warranty);
        System.out.println("Compatibility: " + c10.compatibility);
        System.out.println("Vibration: " + c10.vibrationType);
        System.out.println("Charging: " + c10.chargingType);
    }
}