class NotebookRunner{
	public static void main(String[] args){
		Notebook notebook1 = new Notebook();
		Notebook notebook2 = new Notebook();
		System.out.println(notebook1);
		System.out.println(notebook2);
		System.out.println("\nDetails of Notebook1\n");
		System.out.println("Brand : " + notebook1.brand);
        System.out.println("Color: " + notebook1.color);
        System.out.println("Pages: " + notebook1.numberOfPages);
        System.out.println("Page Type: " + notebook1.pageType);
        System.out.println("Size: " + notebook1.size);
        System.out.println("Price: " + notebook1.price);
        System.out.println("Binding Type: " + notebook1.bindingType);
        System.out.println("Cover Type: " + notebook1.coverType);
        System.out.println("Is Hard Cover: " + notebook1.isHardCover);
        System.out.println("Paper Quality: " + notebook1.paperQuality);
        System.out.println("Ruling Type: " + notebook1.rulingType);
        System.out.println("Orientation: " + notebook1.orientation);
        System.out.println("Subject: " + notebook1.subject);
        System.out.println("Manufacturer: " + notebook1.manufacturer);
        System.out.println("Weight: " + notebook1.weight);
        System.out.println("Dimensions: " + notebook1.dimensions);
        System.out.println("Is Spiral: " + notebook1.isSpiral);
        System.out.println("Design: " + notebook1.design);
        System.out.println("Usage Type: " + notebook1.usageType);
        System.out.println("Country: " + notebook1.countryOfOrigin);
        System.out.println("Warranty: " + notebook1.warrantyPeriod);
        System.out.println("Texture: " + notebook1.texture);
        System.out.println("Eco Friendly: " + notebook1.isEcoFriendly);
        System.out.println("Ink Compatibility: " + notebook1.inkCompatibility);
        System.out.println("Packaging: " + notebook1.packaging);
        System.out.println("Availability: " + notebook1.availability);
		System.out.println("\nNotebook 2 Details:\n");
        System.out.println("Brand: " + notebook2.brand);
        System.out.println("Color: " + notebook2.color);
        System.out.println("Pages: " + notebook2.numberOfPages);
        System.out.println("Page Type: " + notebook2.pageType);
        System.out.println("Size: " + notebook2.size);
        System.out.println("Price: " + notebook2.price);
        System.out.println("Binding Type: " + notebook2.bindingType);
        System.out.println("Cover Type: " + notebook2.coverType);
        System.out.println("Is Hard Cover: " + notebook2.isHardCover);
        System.out.println("Paper Quality: " + notebook2.paperQuality);
        System.out.println("Ruling Type: " + notebook2.rulingType);
        System.out.println("Orientation: " + notebook2.orientation);
        System.out.println("Subject: " + notebook2.subject);
        System.out.println("Manufacturer: " + notebook2.manufacturer);
        System.out.println("Weight: " + notebook2.weight);
        System.out.println("Dimensions: " + notebook2.dimensions);
        System.out.println("Is Spiral: " + notebook2.isSpiral);
        System.out.println("Design: " + notebook2.design);
        System.out.println("Usage Type: " + notebook2.usageType);
        System.out.println("Country: " + notebook2.countryOfOrigin);
        System.out.println("Warranty: " + notebook2.warrantyPeriod);
        System.out.println("Texture: " + notebook2.texture);
        System.out.println("Eco Friendly: " + notebook2.isEcoFriendly);
        System.out.println("Ink Compatibility: " + notebook2.inkCompatibility);
        System.out.println("Packaging: " + notebook2.packaging);
        System.out.println("Availability: " + notebook2.availability);
    }
	}
