class ZipRunner {

    public static void main(String[] args) {

        Zip zip1 = new Zip();
        Zip zip2 = new Zip();
        Zip zip3 = new Zip();
        Zip zip4 = new Zip();
        Zip zip5 = new Zip();
        Zip zip6 = new Zip();
        Zip zip7 = new Zip();
        Zip zip8 = new Zip();
        Zip zip9 = new Zip();
        Zip zip10 = new Zip();

        zip1.price = 50;
        zip1.model = "YKK Classic";
        zip1.teethCount = 30;
        zip1.weight = 0.05;
        zip1.material = "Metal";
        zip1.isAvailable = true;
        zip1.warranty = 1;
        zip1.size = "Small";
        zip1.pullerType = "Standard";
        zip1.lockingType = "None";

        zip2.price = 70;
        zip2.model = "YKK Heavy";
        zip2.teethCount = 40;
        zip2.weight = 0.08;
        zip2.material = "Metal";
        zip2.isAvailable = true;
        zip2.warranty = 2;
        zip2.size = "Medium";
        zip2.pullerType = "Ergonomic";
        zip2.lockingType = "Auto-lock";

        zip3.price = 45;
        zip3.model = "Generic Small";
        zip3.teethCount = 25;
        zip3.weight = 0.04;
        zip3.material = "Plastic";
        zip3.isAvailable = true;
        zip3.warranty = 1;
        zip3.size = "Small";
        zip3.pullerType = "Basic";
        zip3.lockingType = "None";

        zip4.price = 90;
        zip4.model = "Heavy Duty";
        zip4.teethCount = 50;
        zip4.weight = 0.1;
        zip4.material = "Metal";
        zip4.isAvailable = true;
        zip4.warranty = 3;
        zip4.size = "Large";
        zip4.pullerType = "Reinforced";
        zip4.lockingType = "Auto-lock";

        zip5.price = 60;
        zip5.model = "Fashion Zip";
        zip5.teethCount = 35;
        zip5.weight = 0.06;
        zip5.material = "Plastic";
        zip5.isAvailable = true;
        zip5.warranty = 2;
        zip5.size = "Medium";
        zip5.pullerType = "Decorative";
        zip5.lockingType = "None";

        zip6.price = 55;
        zip6.model = "Outdoor Zip";
        zip6.teethCount = 40;
        zip6.weight = 0.07;
        zip6.material = "Metal";
        zip6.isAvailable = true;
        zip6.warranty = 2;
        zip6.size = "Medium";
        zip6.pullerType = "Strong";
        zip6.lockingType = "None";

        zip7.price = 40;
        zip7.model = "Budget Zip";
        zip7.teethCount = 20;
        zip7.weight = 0.03;
        zip7.material = "Plastic";
        zip7.isAvailable = false;
        zip7.warranty = 1;
        zip7.size = "Small";
        zip7.pullerType = "Basic";
        zip7.lockingType = "None";

        zip8.price = 80;
        zip8.model = "Premium Zip";
        zip8.teethCount = 45;
        zip8.weight = 0.09;
        zip8.material = "Metal";
        zip8.isAvailable = true;
        zip8.warranty = 3;
        zip8.size = "Large";
        zip8.pullerType = "Ergonomic";
        zip8.lockingType = "Auto-lock";

        zip9.price = 100;
        zip9.model = "Industrial Zip";
        zip9.teethCount = 60;
        zip9.weight = 0.12;
        zip9.material = "Metal";
        zip9.isAvailable = true;
        zip9.warranty = 5;
        zip9.size = "Extra Large";
        zip9.pullerType = "Reinforced";
        zip9.lockingType = "Auto-lock";

        zip10.price = 35;
        zip10.model = "Mini Zip";
        zip10.teethCount = 15;
        zip10.weight = 0.02;
        zip10.material = "Plastic";
        zip10.isAvailable = true;
        zip10.warranty = 1;
        zip10.size = "Extra Small";
        zip10.pullerType = "Tiny";
        zip10.lockingType = "None";

        System.out.println("\nZip1 Details");
        System.out.println("Brand: " + zip1.brand);
        System.out.println("Color: " + zip1.color);
        System.out.println("Type: " + zip1.type);
        System.out.println("Reusable: " + zip1.isReusable);
        System.out.println("Length: " + zip1.length + " cm");
        System.out.println("Price: " + zip1.price);
        System.out.println("Model: " + zip1.model);
        System.out.println("Teeth Count: " + zip1.teethCount);
        System.out.println("Weight: " + zip1.weight + " kg");
        System.out.println("Material: " + zip1.material);
        System.out.println("Available: " + zip1.isAvailable);
        System.out.println("Warranty: " + zip1.warranty + " year(s)");
        System.out.println("Size: " + zip1.size);
        System.out.println("Puller Type: " + zip1.pullerType);
        System.out.println("Locking Type: " + zip1.lockingType);

        System.out.println("\nZip2 Details");
        System.out.println("Brand: " + zip2.brand);
        System.out.println("Color: " + zip2.color);
        System.out.println("Type: " + zip2.type);
        System.out.println("Reusable: " + zip2.isReusable);
        System.out.println("Length: " + zip2.length + " cm");
        System.out.println("Price: " + zip2.price);
        System.out.println("Model: " + zip2.model);
        System.out.println("Teeth Count: " + zip2.teethCount);
        System.out.println("Weight: " + zip2.weight + " kg");
        System.out.println("Material: " + zip2.material);
        System.out.println("Available: " + zip2.isAvailable);
        System.out.println("Warranty: " + zip2.warranty + " year(s)");
        System.out.println("Size: " + zip2.size);
        System.out.println("Puller Type: " + zip2.pullerType);
        System.out.println("Locking Type: " + zip2.lockingType);

        System.out.println("\nZip3 Details");
        System.out.println("Brand: " + zip3.brand);
        System.out.println("Color: " + zip3.color);
        System.out.println("Type: " + zip3.type);
        System.out.println("Reusable: " + zip3.isReusable);
        System.out.println("Length: " + zip3.length + " cm");
        System.out.println("Price: " + zip3.price);
        System.out.println("Model: " + zip3.model);
        System.out.println("Teeth Count: " + zip3.teethCount);
        System.out.println("Weight: " + zip3.weight + " kg");
        System.out.println("Material: " + zip3.material);
        System.out.println("Available: " + zip3.isAvailable);
        System.out.println("Warranty: " + zip3.warranty + " year(s)");
        System.out.println("Size: " + zip3.size);
        System.out.println("Puller Type: " + zip3.pullerType);
        System.out.println("Locking Type: " + zip3.lockingType);

        System.out.println("\nZip4 Details");
        System.out.println("Brand: " + zip4.brand);
        System.out.println("Color: " + zip4.color);
        System.out.println("Type: " + zip4.type);
        System.out.println("Reusable: " + zip4.isReusable);
        System.out.println("Length: " + zip4.length + " cm");
        System.out.println("Price: " + zip4.price);
        System.out.println("Model: " + zip4.model);
        System.out.println("Teeth Count: " + zip4.teethCount);
        System.out.println("Weight: " + zip4.weight + " kg");
        System.out.println("Material: " + zip4.material);
        System.out.println("Available: " + zip4.isAvailable);
        System.out.println("Warranty: " + zip4.warranty + " year(s)");
        System.out.println("Size: " + zip4.size);
        System.out.println("Puller Type: " + zip4.pullerType);
        System.out.println("Locking Type: " + zip4.lockingType);

        System.out.println("\nZip5 Details");
        System.out.println("Brand: " + zip5.brand);
        System.out.println("Color: " + zip5.color);
        System.out.println("Type: " + zip5.type);
        System.out.println("Reusable: " + zip5.isReusable);
        System.out.println("Length: " + zip5.length + " cm");
        System.out.println("Price: " + zip5.price);
        System.out.println("Model: " + zip5.model);
        System.out.println("Teeth Count: " + zip5.teethCount);
        System.out.println("Weight: " + zip5.weight + " kg");
        System.out.println("Material: " + zip5.material);
        System.out.println("Available: " + zip5.isAvailable);
        System.out.println("Warranty: " + zip5.warranty + " year(s)");
        System.out.println("Size: " + zip5.size);
        System.out.println("Puller Type: " + zip5.pullerType);
        System.out.println("Locking Type: " + zip5.lockingType);

        System.out.println("\nZip6 Details");
        System.out.println("Brand: " + zip6.brand);
        System.out.println("Color: " + zip6.color);
        System.out.println("Type: " + zip6.type);
        System.out.println("Reusable: " + zip6.isReusable);
        System.out.println("Length: " + zip6.length + " cm");
        System.out.println("Price: " + zip6.price);
        System.out.println("Model: " + zip6.model);
        System.out.println("Teeth Count: " + zip6.teethCount);
        System.out.println("Weight: " + zip6.weight + " kg");
        System.out.println("Material: " + zip6.material);
        System.out.println("Available: " + zip6.isAvailable);
        System.out.println("Warranty: " + zip6.warranty + " year(s)");
        System.out.println("Size: " + zip6.size);
        System.out.println("Puller Type: " + zip6.pullerType);
        System.out.println("Locking Type: " + zip6.lockingType);

        System.out.println("\nZip7 Details");
        System.out.println("Brand: " + zip7.brand);
        System.out.println("Color: " + zip7.color);
        System.out.println("Type: " + zip7.type);
        System.out.println("Reusable: " + zip7.isReusable);
        System.out.println("Length: " + zip7.length + " cm");
        System.out.println("Price: " + zip7.price);
        System.out.println("Model: " + zip7.model);
        System.out.println("Teeth Count: " + zip7.teethCount);
        System.out.println("Weight: " + zip7.weight + " kg");
        System.out.println("Material: " + zip7.material);
        System.out.println("Available: " + zip7.isAvailable);
        System.out.println("Warranty: " + zip7.warranty + " year(s)");
        System.out.println("Size: " + zip7.size);
        System.out.println("Puller Type: " + zip7.pullerType);
        System.out.println("Locking Type: " + zip7.lockingType);

        System.out.println("\nZip8 Details");
        System.out.println("Brand: " + zip8.brand);
        System.out.println("Color: " + zip8.color);
        System.out.println("Type: " + zip8.type);
        System.out.println("Reusable: " + zip8.isReusable);
        System.out.println("Length: " + zip8.length + " cm");
        System.out.println("Price: " + zip8.price);
        System.out.println("Model: " + zip8.model);
        System.out.println("Teeth Count: " + zip8.teethCount);
        System.out.println("Weight: " + zip8.weight + " kg");
        System.out.println("Material: " + zip8.material);
        System.out.println("Available: " + zip8.isAvailable);
        System.out.println("Warranty: " + zip8.warranty + " year(s)");
        System.out.println("Size: " + zip8.size);
        System.out.println("Puller Type: " + zip8.pullerType);
        System.out.println("Locking Type: " + zip8.lockingType);
		
        System.out.println("\nZip9 Details");
        System.out.println("Brand: " + zip9.brand);
        System.out.println("Color: " + zip9.color);
        System.out.println("Type: " + zip9.type);
        System.out.println("Reusable: " + zip9.isReusable);
        System.out.println("Length: " + zip9.length + " cm");
        System.out.println("Price: " + zip9.price);
        System.out.println("Model: " + zip9.model);
        System.out.println("Teeth Count: " + zip9.teethCount);
        System.out.println("Weight: " + zip9.weight + " kg");
        System.out.println("Material: " + zip9.material);
        System.out.println("Available: " + zip9.isAvailable);
        System.out.println("Warranty: " + zip9.warranty + " year(s)");
        System.out.println("Size: " + zip9.size);
        System.out.println("Puller Type: " + zip9.pullerType);
        System.out.println("Locking Type: " + zip9.lockingType);
		
        System.out.println("\nZip10 Details");
        System.out.println("Brand: " + zip10.brand);
        System.out.println("Color: " + zip10.color);
        System.out.println("Type: " + zip10.type);
        System.out.println("Reusable: " + zip10.isReusable);
        System.out.println("Length: " + zip10.length + " cm");
        System.out.println("Price: " + zip10.price);
        System.out.println("Model: " + zip10.model);
        System.out.println("Teeth Count: " + zip10.teethCount);
        System.out.println("Weight: " + zip10.weight + " kg");
        System.out.println("Material: " + zip10.material);
        System.out.println("Available: " + zip10.isAvailable);
        System.out.println("Warranty: " + zip10.warranty + " year(s)");
        System.out.println("Size: " + zip10.size);
        System.out.println("Puller Type: " + zip10.pullerType);
        System.out.println("Locking Type: " + zip10.lockingType);
    }
}